# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/dieselfire/dieselfire/simulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/dieselfire/dieselfire/simulator/build_wasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/dieselfire/dieselfire/simulator/build_wasm/CMakeFiles /home/runner/work/dieselfire/dieselfire/simulator/build_wasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/dieselfire/dieselfire/simulator/build_wasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dieselfire-sim

# Build rule for target.
dieselfire-sim: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dieselfire-sim
.PHONY : dieselfire-sim

# fast build rule for target.
dieselfire-sim/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/build
.PHONY : dieselfire-sim/fast

#=============================================================================
# Target rules for targets named bluewire-test

# Build rule for target.
bluewire-test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bluewire-test
.PHONY : bluewire-test

# fast build rule for target.
bluewire-test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/build
.PHONY : bluewire-test/fast

#=============================================================================
# Target rules for targets named lvgl

# Build rule for target.
lvgl: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl
.PHONY : lvgl

# fast build rule for target.
lvgl/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl.dir/build
.PHONY : lvgl/fast

#=============================================================================
# Target rules for targets named lvgl_thorvg

# Build rule for target.
lvgl_thorvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_thorvg
.PHONY : lvgl_thorvg

# fast build rule for target.
lvgl_thorvg/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl_thorvg.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl_thorvg.dir/build
.PHONY : lvgl_thorvg/fast

#=============================================================================
# Target rules for targets named lvgl_examples

# Build rule for target.
lvgl_examples: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_examples
.PHONY : lvgl_examples

# fast build rule for target.
lvgl_examples/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl_examples.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl_examples.dir/build
.PHONY : lvgl_examples/fast

#=============================================================================
# Target rules for targets named lvgl_demos

# Build rule for target.
lvgl_demos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lvgl_demos
.PHONY : lvgl_demos

# fast build rule for target.
lvgl_demos/fast:
	$(MAKE) $(MAKESILENT) -f _deps/lvgl-build/CMakeFiles/lvgl_demos.dir/build.make _deps/lvgl-build/CMakeFiles/lvgl_demos.dir/build
.PHONY : lvgl_demos/fast

bluwire_task.o: bluwire_task.cpp.o
.PHONY : bluwire_task.o

# target to build an object file
bluwire_task.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/bluwire_task.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/bluwire_task.cpp.o
.PHONY : bluwire_task.cpp.o

bluwire_task.i: bluwire_task.cpp.i
.PHONY : bluwire_task.i

# target to preprocess a source file
bluwire_task.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/bluwire_task.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/bluwire_task.cpp.i
.PHONY : bluwire_task.cpp.i

bluwire_task.s: bluwire_task.cpp.s
.PHONY : bluwire_task.s

# target to generate assembly for a file
bluwire_task.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/bluwire_task.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/bluwire_task.cpp.s
.PHONY : bluwire_task.cpp.s

heater_emu.o: heater_emu.cpp.o
.PHONY : heater_emu.o

# target to build an object file
heater_emu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/heater_emu.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/heater_emu.cpp.o
.PHONY : heater_emu.cpp.o

heater_emu.i: heater_emu.cpp.i
.PHONY : heater_emu.i

# target to preprocess a source file
heater_emu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/heater_emu.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/heater_emu.cpp.i
.PHONY : heater_emu.cpp.i

heater_emu.s: heater_emu.cpp.s
.PHONY : heater_emu.s

# target to generate assembly for a file
heater_emu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/heater_emu.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/heater_emu.cpp.s
.PHONY : heater_emu.cpp.s

home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.o: home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.o
.PHONY : home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.o

# target to build an object file
home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.o
.PHONY : home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.o

home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.i: home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.i
.PHONY : home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.i

# target to preprocess a source file
home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.i
.PHONY : home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.i

home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.s: home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.s
.PHONY : home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.s

# target to generate assembly for a file
home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.s
.PHONY : home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.cpp.s

home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.o: home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.o
.PHONY : home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.o

# target to build an object file
home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.o
.PHONY : home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.o

home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.i: home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.i
.PHONY : home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.i

# target to preprocess a source file
home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.i
.PHONY : home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.i

home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.s: home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.s
.PHONY : home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.s

# target to generate assembly for a file
home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.s
.PHONY : home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/main.cpp.s
.PHONY : main.cpp.s

mock/mock_data.o: mock/mock_data.cpp.o
.PHONY : mock/mock_data.o

# target to build an object file
mock/mock_data.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_data.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_data.cpp.o
.PHONY : mock/mock_data.cpp.o

mock/mock_data.i: mock/mock_data.cpp.i
.PHONY : mock/mock_data.i

# target to preprocess a source file
mock/mock_data.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_data.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_data.cpp.i
.PHONY : mock/mock_data.cpp.i

mock/mock_data.s: mock/mock_data.cpp.s
.PHONY : mock/mock_data.s

# target to generate assembly for a file
mock/mock_data.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_data.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_data.cpp.s
.PHONY : mock/mock_data.cpp.s

mock/mock_globals.o: mock/mock_globals.cpp.o
.PHONY : mock/mock_globals.o

# target to build an object file
mock/mock_globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_globals.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_globals.cpp.o
.PHONY : mock/mock_globals.cpp.o

mock/mock_globals.i: mock/mock_globals.cpp.i
.PHONY : mock/mock_globals.i

# target to preprocess a source file
mock/mock_globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_globals.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_globals.cpp.i
.PHONY : mock/mock_globals.cpp.i

mock/mock_globals.s: mock/mock_globals.cpp.s
.PHONY : mock/mock_globals.s

# target to generate assembly for a file
mock/mock_globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_globals.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_globals.cpp.s
.PHONY : mock/mock_globals.cpp.s

mock/mock_tempsense.o: mock/mock_tempsense.cpp.o
.PHONY : mock/mock_tempsense.o

# target to build an object file
mock/mock_tempsense.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_tempsense.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_tempsense.cpp.o
.PHONY : mock/mock_tempsense.cpp.o

mock/mock_tempsense.i: mock/mock_tempsense.cpp.i
.PHONY : mock/mock_tempsense.i

# target to preprocess a source file
mock/mock_tempsense.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_tempsense.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_tempsense.cpp.i
.PHONY : mock/mock_tempsense.cpp.i

mock/mock_tempsense.s: mock/mock_tempsense.cpp.s
.PHONY : mock/mock_tempsense.s

# target to generate assembly for a file
mock/mock_tempsense.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_tempsense.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_tempsense.cpp.s
.PHONY : mock/mock_tempsense.cpp.s

mock/mock_utilclasses.o: mock/mock_utilclasses.cpp.o
.PHONY : mock/mock_utilclasses.o

# target to build an object file
mock/mock_utilclasses.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_utilclasses.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_utilclasses.cpp.o
.PHONY : mock/mock_utilclasses.cpp.o

mock/mock_utilclasses.i: mock/mock_utilclasses.cpp.i
.PHONY : mock/mock_utilclasses.i

# target to preprocess a source file
mock/mock_utilclasses.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_utilclasses.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_utilclasses.cpp.i
.PHONY : mock/mock_utilclasses.cpp.i

mock/mock_utilclasses.s: mock/mock_utilclasses.cpp.s
.PHONY : mock/mock_utilclasses.s

# target to generate assembly for a file
mock/mock_utilclasses.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/mock/mock_utilclasses.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/mock/mock_utilclasses.cpp.s
.PHONY : mock/mock_utilclasses.cpp.s

screens/BTScreen.o: screens/BTScreen.cpp.o
.PHONY : screens/BTScreen.o

# target to build an object file
screens/BTScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/BTScreen.cpp.o
.PHONY : screens/BTScreen.cpp.o

screens/BTScreen.i: screens/BTScreen.cpp.i
.PHONY : screens/BTScreen.i

# target to preprocess a source file
screens/BTScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/BTScreen.cpp.i
.PHONY : screens/BTScreen.cpp.i

screens/BTScreen.s: screens/BTScreen.cpp.s
.PHONY : screens/BTScreen.s

# target to generate assembly for a file
screens/BTScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/BTScreen.cpp.s
.PHONY : screens/BTScreen.cpp.s

screens/BWDebugScreen.o: screens/BWDebugScreen.cpp.o
.PHONY : screens/BWDebugScreen.o

# target to build an object file
screens/BWDebugScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/BWDebugScreen.cpp.o
.PHONY : screens/BWDebugScreen.cpp.o

screens/BWDebugScreen.i: screens/BWDebugScreen.cpp.i
.PHONY : screens/BWDebugScreen.i

# target to preprocess a source file
screens/BWDebugScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/BWDebugScreen.cpp.i
.PHONY : screens/BWDebugScreen.cpp.i

screens/BWDebugScreen.s: screens/BWDebugScreen.cpp.s
.PHONY : screens/BWDebugScreen.s

# target to generate assembly for a file
screens/BWDebugScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/BWDebugScreen.cpp.s
.PHONY : screens/BWDebugScreen.cpp.s

screens/DieselScreen.o: screens/DieselScreen.cpp.o
.PHONY : screens/DieselScreen.o

# target to build an object file
screens/DieselScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/DieselScreen.cpp.o
.PHONY : screens/DieselScreen.cpp.o

screens/DieselScreen.i: screens/DieselScreen.cpp.i
.PHONY : screens/DieselScreen.i

# target to preprocess a source file
screens/DieselScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/DieselScreen.cpp.i
.PHONY : screens/DieselScreen.cpp.i

screens/DieselScreen.s: screens/DieselScreen.cpp.s
.PHONY : screens/DieselScreen.s

# target to generate assembly for a file
screens/DieselScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/DieselScreen.cpp.s
.PHONY : screens/DieselScreen.cpp.s

screens/FrostScreen.o: screens/FrostScreen.cpp.o
.PHONY : screens/FrostScreen.o

# target to build an object file
screens/FrostScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FrostScreen.cpp.o
.PHONY : screens/FrostScreen.cpp.o

screens/FrostScreen.i: screens/FrostScreen.cpp.i
.PHONY : screens/FrostScreen.i

# target to preprocess a source file
screens/FrostScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FrostScreen.cpp.i
.PHONY : screens/FrostScreen.cpp.i

screens/FrostScreen.s: screens/FrostScreen.cpp.s
.PHONY : screens/FrostScreen.s

# target to generate assembly for a file
screens/FrostScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FrostScreen.cpp.s
.PHONY : screens/FrostScreen.cpp.s

screens/FuelCalScreen.o: screens/FuelCalScreen.cpp.o
.PHONY : screens/FuelCalScreen.o

# target to build an object file
screens/FuelCalScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FuelCalScreen.cpp.o
.PHONY : screens/FuelCalScreen.cpp.o

screens/FuelCalScreen.i: screens/FuelCalScreen.cpp.i
.PHONY : screens/FuelCalScreen.i

# target to preprocess a source file
screens/FuelCalScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FuelCalScreen.cpp.i
.PHONY : screens/FuelCalScreen.cpp.i

screens/FuelCalScreen.s: screens/FuelCalScreen.cpp.s
.PHONY : screens/FuelCalScreen.s

# target to generate assembly for a file
screens/FuelCalScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FuelCalScreen.cpp.s
.PHONY : screens/FuelCalScreen.cpp.s

screens/FuelMixtureScreen.o: screens/FuelMixtureScreen.cpp.o
.PHONY : screens/FuelMixtureScreen.o

# target to build an object file
screens/FuelMixtureScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FuelMixtureScreen.cpp.o
.PHONY : screens/FuelMixtureScreen.cpp.o

screens/FuelMixtureScreen.i: screens/FuelMixtureScreen.cpp.i
.PHONY : screens/FuelMixtureScreen.i

# target to preprocess a source file
screens/FuelMixtureScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FuelMixtureScreen.cpp.i
.PHONY : screens/FuelMixtureScreen.cpp.i

screens/FuelMixtureScreen.s: screens/FuelMixtureScreen.cpp.s
.PHONY : screens/FuelMixtureScreen.s

# target to generate assembly for a file
screens/FuelMixtureScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/FuelMixtureScreen.cpp.s
.PHONY : screens/FuelMixtureScreen.cpp.s

screens/GPIOScreen.o: screens/GPIOScreen.cpp.o
.PHONY : screens/GPIOScreen.o

# target to build an object file
screens/GPIOScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/GPIOScreen.cpp.o
.PHONY : screens/GPIOScreen.cpp.o

screens/GPIOScreen.i: screens/GPIOScreen.cpp.i
.PHONY : screens/GPIOScreen.i

# target to preprocess a source file
screens/GPIOScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/GPIOScreen.cpp.i
.PHONY : screens/GPIOScreen.cpp.i

screens/GPIOScreen.s: screens/GPIOScreen.cpp.s
.PHONY : screens/GPIOScreen.s

# target to generate assembly for a file
screens/GPIOScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/GPIOScreen.cpp.s
.PHONY : screens/GPIOScreen.cpp.s

screens/HeaterSettingsScreen.o: screens/HeaterSettingsScreen.cpp.o
.PHONY : screens/HeaterSettingsScreen.o

# target to build an object file
screens/HeaterSettingsScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HeaterSettingsScreen.cpp.o
.PHONY : screens/HeaterSettingsScreen.cpp.o

screens/HeaterSettingsScreen.i: screens/HeaterSettingsScreen.cpp.i
.PHONY : screens/HeaterSettingsScreen.i

# target to preprocess a source file
screens/HeaterSettingsScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HeaterSettingsScreen.cpp.i
.PHONY : screens/HeaterSettingsScreen.cpp.i

screens/HeaterSettingsScreen.s: screens/HeaterSettingsScreen.cpp.s
.PHONY : screens/HeaterSettingsScreen.s

# target to generate assembly for a file
screens/HeaterSettingsScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HeaterSettingsScreen.cpp.s
.PHONY : screens/HeaterSettingsScreen.cpp.s

screens/HourMeterScreen.o: screens/HourMeterScreen.cpp.o
.PHONY : screens/HourMeterScreen.o

# target to build an object file
screens/HourMeterScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HourMeterScreen.cpp.o
.PHONY : screens/HourMeterScreen.cpp.o

screens/HourMeterScreen.i: screens/HourMeterScreen.cpp.i
.PHONY : screens/HourMeterScreen.i

# target to preprocess a source file
screens/HourMeterScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HourMeterScreen.cpp.i
.PHONY : screens/HourMeterScreen.cpp.i

screens/HourMeterScreen.s: screens/HourMeterScreen.cpp.s
.PHONY : screens/HourMeterScreen.s

# target to generate assembly for a file
screens/HourMeterScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HourMeterScreen.cpp.s
.PHONY : screens/HourMeterScreen.cpp.s

screens/HumidityScreen.o: screens/HumidityScreen.cpp.o
.PHONY : screens/HumidityScreen.o

# target to build an object file
screens/HumidityScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HumidityScreen.cpp.o
.PHONY : screens/HumidityScreen.cpp.o

screens/HumidityScreen.i: screens/HumidityScreen.cpp.i
.PHONY : screens/HumidityScreen.i

# target to preprocess a source file
screens/HumidityScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HumidityScreen.cpp.i
.PHONY : screens/HumidityScreen.cpp.i

screens/HumidityScreen.s: screens/HumidityScreen.cpp.s
.PHONY : screens/HumidityScreen.s

# target to generate assembly for a file
screens/HumidityScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/HumidityScreen.cpp.s
.PHONY : screens/HumidityScreen.cpp.s

screens/InheritScreen.o: screens/InheritScreen.cpp.o
.PHONY : screens/InheritScreen.o

# target to build an object file
screens/InheritScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/InheritScreen.cpp.o
.PHONY : screens/InheritScreen.cpp.o

screens/InheritScreen.i: screens/InheritScreen.cpp.i
.PHONY : screens/InheritScreen.i

# target to preprocess a source file
screens/InheritScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/InheritScreen.cpp.i
.PHONY : screens/InheritScreen.cpp.i

screens/InheritScreen.s: screens/InheritScreen.cpp.s
.PHONY : screens/InheritScreen.s

# target to generate assembly for a file
screens/InheritScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/InheritScreen.cpp.s
.PHONY : screens/InheritScreen.cpp.s

screens/LVCScreen.o: screens/LVCScreen.cpp.o
.PHONY : screens/LVCScreen.o

# target to build an object file
screens/LVCScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/LVCScreen.cpp.o
.PHONY : screens/LVCScreen.cpp.o

screens/LVCScreen.i: screens/LVCScreen.cpp.i
.PHONY : screens/LVCScreen.i

# target to preprocess a source file
screens/LVCScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/LVCScreen.cpp.i
.PHONY : screens/LVCScreen.cpp.i

screens/LVCScreen.s: screens/LVCScreen.cpp.s
.PHONY : screens/LVCScreen.s

# target to generate assembly for a file
screens/LVCScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/LVCScreen.cpp.s
.PHONY : screens/LVCScreen.cpp.s

screens/MQTTScreen.o: screens/MQTTScreen.cpp.o
.PHONY : screens/MQTTScreen.o

# target to build an object file
screens/MQTTScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/MQTTScreen.cpp.o
.PHONY : screens/MQTTScreen.cpp.o

screens/MQTTScreen.i: screens/MQTTScreen.cpp.i
.PHONY : screens/MQTTScreen.i

# target to preprocess a source file
screens/MQTTScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/MQTTScreen.cpp.i
.PHONY : screens/MQTTScreen.cpp.i

screens/MQTTScreen.s: screens/MQTTScreen.cpp.s
.PHONY : screens/MQTTScreen.s

# target to generate assembly for a file
screens/MQTTScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/MQTTScreen.cpp.s
.PHONY : screens/MQTTScreen.cpp.s

screens/MainStatusScreen.o: screens/MainStatusScreen.cpp.o
.PHONY : screens/MainStatusScreen.o

# target to build an object file
screens/MainStatusScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/MainStatusScreen.cpp.o
.PHONY : screens/MainStatusScreen.cpp.o

screens/MainStatusScreen.i: screens/MainStatusScreen.cpp.i
.PHONY : screens/MainStatusScreen.i

# target to preprocess a source file
screens/MainStatusScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/MainStatusScreen.cpp.i
.PHONY : screens/MainStatusScreen.cpp.i

screens/MainStatusScreen.s: screens/MainStatusScreen.cpp.s
.PHONY : screens/MainStatusScreen.s

# target to generate assembly for a file
screens/MainStatusScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/MainStatusScreen.cpp.s
.PHONY : screens/MainStatusScreen.cpp.s

screens/PasswordScreen.o: screens/PasswordScreen.cpp.o
.PHONY : screens/PasswordScreen.o

# target to build an object file
screens/PasswordScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/PasswordScreen.cpp.o
.PHONY : screens/PasswordScreen.cpp.o

screens/PasswordScreen.i: screens/PasswordScreen.cpp.i
.PHONY : screens/PasswordScreen.i

# target to preprocess a source file
screens/PasswordScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/PasswordScreen.cpp.i
.PHONY : screens/PasswordScreen.cpp.i

screens/PasswordScreen.s: screens/PasswordScreen.cpp.s
.PHONY : screens/PasswordScreen.s

# target to generate assembly for a file
screens/PasswordScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/PasswordScreen.cpp.s
.PHONY : screens/PasswordScreen.cpp.s

screens/RebootScreen.o: screens/RebootScreen.cpp.o
.PHONY : screens/RebootScreen.o

# target to build an object file
screens/RebootScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/RebootScreen.cpp.o
.PHONY : screens/RebootScreen.cpp.o

screens/RebootScreen.i: screens/RebootScreen.cpp.i
.PHONY : screens/RebootScreen.i

# target to preprocess a source file
screens/RebootScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/RebootScreen.cpp.i
.PHONY : screens/RebootScreen.cpp.i

screens/RebootScreen.s: screens/RebootScreen.cpp.s
.PHONY : screens/RebootScreen.s

# target to generate assembly for a file
screens/RebootScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/RebootScreen.cpp.s
.PHONY : screens/RebootScreen.cpp.s

screens/SensorScreen.o: screens/SensorScreen.cpp.o
.PHONY : screens/SensorScreen.o

# target to build an object file
screens/SensorScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SensorScreen.cpp.o
.PHONY : screens/SensorScreen.cpp.o

screens/SensorScreen.i: screens/SensorScreen.cpp.i
.PHONY : screens/SensorScreen.i

# target to preprocess a source file
screens/SensorScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SensorScreen.cpp.i
.PHONY : screens/SensorScreen.cpp.i

screens/SensorScreen.s: screens/SensorScreen.cpp.s
.PHONY : screens/SensorScreen.s

# target to generate assembly for a file
screens/SensorScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SensorScreen.cpp.s
.PHONY : screens/SensorScreen.cpp.s

screens/SettingsMenuScreen.o: screens/SettingsMenuScreen.cpp.o
.PHONY : screens/SettingsMenuScreen.o

# target to build an object file
screens/SettingsMenuScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SettingsMenuScreen.cpp.o
.PHONY : screens/SettingsMenuScreen.cpp.o

screens/SettingsMenuScreen.i: screens/SettingsMenuScreen.cpp.i
.PHONY : screens/SettingsMenuScreen.i

# target to preprocess a source file
screens/SettingsMenuScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SettingsMenuScreen.cpp.i
.PHONY : screens/SettingsMenuScreen.cpp.i

screens/SettingsMenuScreen.s: screens/SettingsMenuScreen.cpp.s
.PHONY : screens/SettingsMenuScreen.s

# target to generate assembly for a file
screens/SettingsMenuScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SettingsMenuScreen.cpp.s
.PHONY : screens/SettingsMenuScreen.cpp.s

screens/SystemScreen.o: screens/SystemScreen.cpp.o
.PHONY : screens/SystemScreen.o

# target to build an object file
screens/SystemScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SystemScreen.cpp.o
.PHONY : screens/SystemScreen.cpp.o

screens/SystemScreen.i: screens/SystemScreen.cpp.i
.PHONY : screens/SystemScreen.i

# target to preprocess a source file
screens/SystemScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SystemScreen.cpp.i
.PHONY : screens/SystemScreen.cpp.i

screens/SystemScreen.s: screens/SystemScreen.cpp.s
.PHONY : screens/SystemScreen.s

# target to generate assembly for a file
screens/SystemScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/SystemScreen.cpp.s
.PHONY : screens/SystemScreen.cpp.s

screens/ThermostatScreen.o: screens/ThermostatScreen.cpp.o
.PHONY : screens/ThermostatScreen.o

# target to build an object file
screens/ThermostatScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/ThermostatScreen.cpp.o
.PHONY : screens/ThermostatScreen.cpp.o

screens/ThermostatScreen.i: screens/ThermostatScreen.cpp.i
.PHONY : screens/ThermostatScreen.i

# target to preprocess a source file
screens/ThermostatScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/ThermostatScreen.cpp.i
.PHONY : screens/ThermostatScreen.cpp.i

screens/ThermostatScreen.s: screens/ThermostatScreen.cpp.s
.PHONY : screens/ThermostatScreen.s

# target to generate assembly for a file
screens/ThermostatScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/ThermostatScreen.cpp.s
.PHONY : screens/ThermostatScreen.cpp.s

screens/TimeoutsScreen.o: screens/TimeoutsScreen.cpp.o
.PHONY : screens/TimeoutsScreen.o

# target to build an object file
screens/TimeoutsScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimeoutsScreen.cpp.o
.PHONY : screens/TimeoutsScreen.cpp.o

screens/TimeoutsScreen.i: screens/TimeoutsScreen.cpp.i
.PHONY : screens/TimeoutsScreen.i

# target to preprocess a source file
screens/TimeoutsScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimeoutsScreen.cpp.i
.PHONY : screens/TimeoutsScreen.cpp.i

screens/TimeoutsScreen.s: screens/TimeoutsScreen.cpp.s
.PHONY : screens/TimeoutsScreen.s

# target to generate assembly for a file
screens/TimeoutsScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimeoutsScreen.cpp.s
.PHONY : screens/TimeoutsScreen.cpp.s

screens/TimerChartScreen.o: screens/TimerChartScreen.cpp.o
.PHONY : screens/TimerChartScreen.o

# target to build an object file
screens/TimerChartScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimerChartScreen.cpp.o
.PHONY : screens/TimerChartScreen.cpp.o

screens/TimerChartScreen.i: screens/TimerChartScreen.cpp.i
.PHONY : screens/TimerChartScreen.i

# target to preprocess a source file
screens/TimerChartScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimerChartScreen.cpp.i
.PHONY : screens/TimerChartScreen.cpp.i

screens/TimerChartScreen.s: screens/TimerChartScreen.cpp.s
.PHONY : screens/TimerChartScreen.s

# target to generate assembly for a file
screens/TimerChartScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimerChartScreen.cpp.s
.PHONY : screens/TimerChartScreen.cpp.s

screens/TimerEditScreen.o: screens/TimerEditScreen.cpp.o
.PHONY : screens/TimerEditScreen.o

# target to build an object file
screens/TimerEditScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimerEditScreen.cpp.o
.PHONY : screens/TimerEditScreen.cpp.o

screens/TimerEditScreen.i: screens/TimerEditScreen.cpp.i
.PHONY : screens/TimerEditScreen.i

# target to preprocess a source file
screens/TimerEditScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimerEditScreen.cpp.i
.PHONY : screens/TimerEditScreen.cpp.i

screens/TimerEditScreen.s: screens/TimerEditScreen.cpp.s
.PHONY : screens/TimerEditScreen.s

# target to generate assembly for a file
screens/TimerEditScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/TimerEditScreen.cpp.s
.PHONY : screens/TimerEditScreen.cpp.s

screens/WiFiScreen.o: screens/WiFiScreen.cpp.o
.PHONY : screens/WiFiScreen.o

# target to build an object file
screens/WiFiScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/WiFiScreen.cpp.o
.PHONY : screens/WiFiScreen.cpp.o

screens/WiFiScreen.i: screens/WiFiScreen.cpp.i
.PHONY : screens/WiFiScreen.i

# target to preprocess a source file
screens/WiFiScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/WiFiScreen.cpp.i
.PHONY : screens/WiFiScreen.cpp.i

screens/WiFiScreen.s: screens/WiFiScreen.cpp.s
.PHONY : screens/WiFiScreen.s

# target to generate assembly for a file
screens/WiFiScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/screens/WiFiScreen.cpp.s
.PHONY : screens/WiFiScreen.cpp.s

test_bluewire.o: test_bluewire.cpp.o
.PHONY : test_bluewire.o

# target to build an object file
test_bluewire.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/test_bluewire.cpp.o
.PHONY : test_bluewire.cpp.o

test_bluewire.i: test_bluewire.cpp.i
.PHONY : test_bluewire.i

# target to preprocess a source file
test_bluewire.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/test_bluewire.cpp.i
.PHONY : test_bluewire.cpp.i

test_bluewire.s: test_bluewire.cpp.s
.PHONY : test_bluewire.s

# target to generate assembly for a file
test_bluewire.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/test_bluewire.cpp.s
.PHONY : test_bluewire.cpp.s

vserial.o: vserial.cpp.o
.PHONY : vserial.o

# target to build an object file
vserial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/vserial.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/vserial.cpp.o
.PHONY : vserial.cpp.o

vserial.i: vserial.cpp.i
.PHONY : vserial.i

# target to preprocess a source file
vserial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/vserial.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/vserial.cpp.i
.PHONY : vserial.cpp.i

vserial.s: vserial.cpp.s
.PHONY : vserial.s

# target to generate assembly for a file
vserial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dieselfire-sim.dir/build.make CMakeFiles/dieselfire-sim.dir/vserial.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bluewire-test.dir/build.make CMakeFiles/bluewire-test.dir/vserial.cpp.s
.PHONY : vserial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... bluewire-test"
	@echo "... dieselfire-sim"
	@echo "... lvgl"
	@echo "... lvgl_demos"
	@echo "... lvgl_examples"
	@echo "... lvgl_thorvg"
	@echo "... bluwire_task.o"
	@echo "... bluwire_task.i"
	@echo "... bluwire_task.s"
	@echo "... heater_emu.o"
	@echo "... heater_emu.i"
	@echo "... heater_emu.s"
	@echo "... home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.o"
	@echo "... home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.i"
	@echo "... home/runner/work/dieselfire/dieselfire/src/Protocol/Protocol.s"
	@echo "... home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.o"
	@echo "... home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.i"
	@echo "... home/runner/work/dieselfire/dieselfire/src/Utility/MODBUS-CRC16.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mock/mock_data.o"
	@echo "... mock/mock_data.i"
	@echo "... mock/mock_data.s"
	@echo "... mock/mock_globals.o"
	@echo "... mock/mock_globals.i"
	@echo "... mock/mock_globals.s"
	@echo "... mock/mock_tempsense.o"
	@echo "... mock/mock_tempsense.i"
	@echo "... mock/mock_tempsense.s"
	@echo "... mock/mock_utilclasses.o"
	@echo "... mock/mock_utilclasses.i"
	@echo "... mock/mock_utilclasses.s"
	@echo "... screens/BTScreen.o"
	@echo "... screens/BTScreen.i"
	@echo "... screens/BTScreen.s"
	@echo "... screens/BWDebugScreen.o"
	@echo "... screens/BWDebugScreen.i"
	@echo "... screens/BWDebugScreen.s"
	@echo "... screens/DieselScreen.o"
	@echo "... screens/DieselScreen.i"
	@echo "... screens/DieselScreen.s"
	@echo "... screens/FrostScreen.o"
	@echo "... screens/FrostScreen.i"
	@echo "... screens/FrostScreen.s"
	@echo "... screens/FuelCalScreen.o"
	@echo "... screens/FuelCalScreen.i"
	@echo "... screens/FuelCalScreen.s"
	@echo "... screens/FuelMixtureScreen.o"
	@echo "... screens/FuelMixtureScreen.i"
	@echo "... screens/FuelMixtureScreen.s"
	@echo "... screens/GPIOScreen.o"
	@echo "... screens/GPIOScreen.i"
	@echo "... screens/GPIOScreen.s"
	@echo "... screens/HeaterSettingsScreen.o"
	@echo "... screens/HeaterSettingsScreen.i"
	@echo "... screens/HeaterSettingsScreen.s"
	@echo "... screens/HourMeterScreen.o"
	@echo "... screens/HourMeterScreen.i"
	@echo "... screens/HourMeterScreen.s"
	@echo "... screens/HumidityScreen.o"
	@echo "... screens/HumidityScreen.i"
	@echo "... screens/HumidityScreen.s"
	@echo "... screens/InheritScreen.o"
	@echo "... screens/InheritScreen.i"
	@echo "... screens/InheritScreen.s"
	@echo "... screens/LVCScreen.o"
	@echo "... screens/LVCScreen.i"
	@echo "... screens/LVCScreen.s"
	@echo "... screens/MQTTScreen.o"
	@echo "... screens/MQTTScreen.i"
	@echo "... screens/MQTTScreen.s"
	@echo "... screens/MainStatusScreen.o"
	@echo "... screens/MainStatusScreen.i"
	@echo "... screens/MainStatusScreen.s"
	@echo "... screens/PasswordScreen.o"
	@echo "... screens/PasswordScreen.i"
	@echo "... screens/PasswordScreen.s"
	@echo "... screens/RebootScreen.o"
	@echo "... screens/RebootScreen.i"
	@echo "... screens/RebootScreen.s"
	@echo "... screens/SensorScreen.o"
	@echo "... screens/SensorScreen.i"
	@echo "... screens/SensorScreen.s"
	@echo "... screens/SettingsMenuScreen.o"
	@echo "... screens/SettingsMenuScreen.i"
	@echo "... screens/SettingsMenuScreen.s"
	@echo "... screens/SystemScreen.o"
	@echo "... screens/SystemScreen.i"
	@echo "... screens/SystemScreen.s"
	@echo "... screens/ThermostatScreen.o"
	@echo "... screens/ThermostatScreen.i"
	@echo "... screens/ThermostatScreen.s"
	@echo "... screens/TimeoutsScreen.o"
	@echo "... screens/TimeoutsScreen.i"
	@echo "... screens/TimeoutsScreen.s"
	@echo "... screens/TimerChartScreen.o"
	@echo "... screens/TimerChartScreen.i"
	@echo "... screens/TimerChartScreen.s"
	@echo "... screens/TimerEditScreen.o"
	@echo "... screens/TimerEditScreen.i"
	@echo "... screens/TimerEditScreen.s"
	@echo "... screens/WiFiScreen.o"
	@echo "... screens/WiFiScreen.i"
	@echo "... screens/WiFiScreen.s"
	@echo "... test_bluewire.o"
	@echo "... test_bluewire.i"
	@echo "... test_bluewire.s"
	@echo "... vserial.o"
	@echo "... vserial.i"
	@echo "... vserial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

