
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Linux - 6.17.0-1015-azure - x86_64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is GNU using "--version" did not match "(GNU assembler)|(GCC)|(Free Software Foundation)":
      shared:INFO: (Emscripten: Running sanity checks)
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is AppleClang using "--version" did not match "(Apple (clang|LLVM) version)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is Clang using "--version" did not match "(clang version)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is ARMClang using "--version" did not match "armclang":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is OrangeC using "--version" did not match "occ \\(OrangeC\\) Version":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is HP using "-V" did not match "HP C":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is Intel using "--version" did not match "(ICC)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is IntelLLVM using "--version" did not match "(Intel[^
      ]+oneAPI)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is SunPro using "-V" did not match "Sun C":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is XL using "-qversion" did not match "XL C":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is MSVC using "-?" did not match "Microsoft":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is TI using "-h" did not match "Texas Instruments":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is TIClang using "--version" did not match "(TI (.*) Clang Compiler)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is IAR using "" did not match "IAR Assembler":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is ARMCC using "" did not match "(ARM Compiler)|(ARM Assembler)|(Arm Compiler)":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is NASM using "-v" did not match "(NASM version)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      clang version 23.0.0git (https:/github.com/llvm/llvm-project 7b58716d96c3ae4c0c4e6f72e29b16137bb6224b)
      Target: wasm32-unknown-emscripten
      Thread model: posix
      InstalledDir: /home/runner/work/_temp/7609d078-96d3-4c6e-84ca-591f726c196e/emsdk-main/upstream/bin
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is YASM using "--version" did not match "(yasm)":
      emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 5.0.7 (263db4cffa6f9fc2ec514a70abac81362ea41849)
      Copyright (C) 2026 the Emscripten authors (see AUTHORS.txt)
      This is free and open source software under the MIT license.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is ADSP using "-version" did not match "Analog Devices":
      emcc: error: no input files
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineCompilerId.cmake:1250 (message)"
      - "/usr/local/share/cmake-3.31/Modules/CMakeDetermineASMCompiler.cmake:135 (CMAKE_DETERMINE_COMPILER_ID_VENDOR)"
      - "build_wasm/_deps/lvgl-src/CMakeLists.txt:13 (enable_language)"
    message: |
      Checking whether the ASM compiler is QCC using "-V" did not match "gcc_nto":
      emcc: error: no input files
...
